version: '3.8'

services:

  scylladb:
    image: "scylladb/scylla"
    ports:
     - "9042:9042"
    volumes:
     - /var/lib/scylla:/var/lib/scylla
    restart: always
    command: '--experimental 1'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
  